const width = 5;
const height = 8;
const area = width * height;
console.log(area, typeof area);
const payment = 10;
const bill = 5;
const change = payment - bill;
console.log(change, typeof change);
const quizzes = 20;
const midterm = 30;
const final = 50;
const grade = (quizzes + midterm + final) / 3;
console.log(grade, typeof grade);
const firstName = 'Lambert';
const lastName = 'Nguyen';
const fullName = firstName + ' ' + lastName;
console.log(fullName, typeof fullName);
const pH = 5;
const isAcidic = pH < 7;
console.log(isAcidic, typeof isAcidic);
const headCount = 10;
const isSparta = headCount === 300;
console.log(isSparta, typeof isSparta);
const motto = fullName + ' is the GOAT';
console.log(motto, typeof motto);
